export default {
  // Auth response status
  EMAIL_ERR: "EMAIL_ERR",
  PASSWORD_ERR: "PASSWORD_ERR",
  USER_ERR: "USER_ERR",
  AUTH_ERR: "AUTH_ERR",

  // Response status
  SERVER_ERR: "SERVER_ERR",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  FORBIDDEN: "FORBIDDEN",

  // Product response status
  PRODUCT_NAME_ERR: "PRODUCT_NAME_ERR",
  PRODUCT_DESC_ERR: "PRODUCT_DESC_ERR",
  PRODUCT_PRICE_ERR: "PRODUCT_PRICE_ERR",
  PRODUCT_IMAGES_ERR: "PRODUCT_IMAGES_ERR",

  // Order response status
  ORDER_PRODUCTS_ERR: "ORDER_PRODUCTS_ERR",
};